name: Build and Run Python Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          #          - 3.7
          #          - 3.8
          - 3.9
          - 3.10.11
          - 3.11
          - 3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get install -y portaudio19-dev ffmpeg  # PortAudio - required

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #      - name: Run tests
      #        run: |
      #          python -m unittest discover  # Uruchamia testy jednostkowe (jeśli są w projekcie)

      - name: Build and run the project
        run: |
          python main.py

    timeout-minutes: 5
